### ISSUE TITLE
IDEA : Dockerize that connector

### ISSUE THREAD

**Issue by vperrinfr** [hmatheisen/iadvize-connector-v2#2]
Hi,

Could you provide Docker file to be able to have a docker of your connector ?

Thanks

**Comment by hmatheisen** [comment]
Good idea, I'll do it ASAP :ok_hand:

**Comment by hmatheisen** [comment]
Done !
[hmatheisen/iadvize-connector](https://cloud.docker.com/u/hmatheisen/repository/docker/hmatheisen/iadvize-connector)
